### ISSUE TITLE
Carbon X1 with hdpi

### ISSUE THREAD

**Issue by simao** [mohlerm/dotfiles#1]
Hi,

Sorry to open an issue for this but I thought maybe you could answer some questions about using your x1 with hdpi?

Does it work well with i3 or do you need lots of workarounds to make it work?

Does it work with an external monitor?

Thanks in advance.

Simao

**Comment by mohlerm** [comment]
Hi simao,

it's fine that you've opened an issue, I gladly help wherever I can.

Unfortunately I don't have a X1 with a HiDPI screen. My screen resolution is 1600x900 and everything is working nicely.
Multiple monitors also work nice, I've wrote a udev rule / script that does the work for me.
I've pushed them to my git so you can take a look:
https://github.com/mohlerm/dotfiles/commit/f63435787d159eedba370f53267e681127c889ee
This gets triggered when I connect my USB Hub which is usually at the same time I connect my monitor. There are more elegant solutions but this one works fine so I don't see a reason to improve it further.

Cheers

**Comment by simao** [comment]
Hi,
Ah ok, I thought you had the last gen model.

Thanks for the udev rule, it's useful for my current setup :)

Cheers,
Simao
